---
version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=133
      - MYSQL_ROOT_PASSWORD=homeLab65
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=lab #optional
      - MYSQL_USER=homeLab65 #optional
      - MYSQL_PASSWORD=homeLab65 #optional
    - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /home/lab/docker/mariadb/data:/config
    ports:
      - 3306:3306
    restart: unless-stopped