version: "2.1"
services:
# Guacamole Daemon - Needed for Guacamole
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - -nginxproxy_default
    volumes:
      - /home/lab/docker/guacd/data:/config