---
version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=homeLab65
      - TZ=Europe/London
      - MYSQL_DATABASE=guca #optional
      - MYSQL_USER=lab #optional
      - MYSQL_PASSWORD=homeLab #optional
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /home/lab/docker/mariadb/data:/config
    network:
      - nginxproxy_defaults
    ports:
      - 3306:3306
    restart: unless-stopped